[package]
name = "laver"
version = "0.1.0"
edition = "2021"

[dependencies]
num-bigint = "0.4"
num-integer = "0.1"
num-traits = "0.2"

[lints.clippy]
undocumented_unsafe_blocks = "deny"
pedantic = { priority = -1, level = "warn" }
nursery = { priority = -2, level = "warn" }
